name: Book Tennis Court

on:
  schedule:
    - cron: "0 15 * * 1"  # Monday 15:00 UTC = 19:00 GST
    - cron: "0 16 * * 1"  # Monday 16:00 UTC = 20:00 GST
    - cron: "0 12 * * 4"  # Thursday 12:00 UTC = 16:00 GST
    - cron: "0 13 * * 4"  # Thursday 13:00 UTC = 17:00 GST
  workflow_dispatch:

jobs:
  book-slot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Set up Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
          # Retry wget up to 3 times with verbose output
          for i in {1..3}; do
            wget "https://chromedriver.storage.googleapis.com/133.0.6943.90/chromedriver_linux64.zip" && break
            echo "wget attempt $i failed, retrying..."
            sleep 2
          done
          ls -la
          unzip chromedriver_linux64.zip || { echo "unzip failed"; exit 1; }
          sudo mv chromedriver /usr/local/bin/ || { echo "mv failed"; exit 1; }
          sudo chmod +x /usr/local/bin/chromedriver || { echo "chmod failed"; exit 1; }
          chromedriver --version
      - name: Run booking script
        env:
          CALENDLY_URL: ${{ secrets.CALENDLY_URL }}
          FULL_NAME_1: ${{ secrets.FULL_NAME_1 }}
          EMAIL_1: ${{ secrets.EMAIL_1 }}
          BUILDING_NAME_1: ${{ secrets.BUILDING_NAME_1 }}
          UNIT_NO_1: ${{ secrets.UNIT_NO_1 }}
          NUM_PLAYERS_1: ${{ secrets.NUM_PLAYERS_1 }}
          PHONE_NO_1: ${{ secrets.PHONE_NO_1 }}
          FULL_NAME_2: ${{ secrets.FULL_NAME_2 }}
          EMAIL_2: ${{ secrets.EMAIL_2 }}
          BUILDING_NAME_2: ${{ secrets.BUILDING_NAME_2 }}
          UNIT_NO_2: ${{ secrets.UNIT_NO_2 }}
          NUM_PLAYERS_2: ${{ secrets.NUM_PLAYERS_2 }}
          PHONE_NO_2: ${{ secrets.PHONE_NO_2 }}
        run: |
          CURRENT_TIME=$(date -u +"%A %H:%M")
          echo "Current time: $CURRENT_TIME"
          python tennis_bot.py "$CURRENT_TIME"
